languageCode = "en-us"
title = "Mythical Angular"
theme = "cactus"
copyright = "Kamil Gałek"
baseURL = "https://mythical-angular.dev"
googleAnalytics = "G-X7BCK4L1CF"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "GitHub"
url = "https://github.com/galczo5"
weight = 4

[params]
  mainSection = "posts"
  colortheme = "white"
  logo = "logo.jpeg"
  css = ["css/custom.css"]
  postsOnHomePage = 10

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

